services:
  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD:-docker}
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD:-docker}"]
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data
